---
  - name: disable & stop systemd
    shell: |
        systemctl --user stop container-nextjs-instance \
        && systemctl --user disable container-nextjs-instance \
        && podman stop nextjs-container \
        && podman rm nextjs-container
    failed_when: false
        
  - name: remove file
    shell: |
        rm /home/admin/.config/systemd/user/container-nextjs-instance.service
    failed_when: false
    
  - name: systemctl daemon-reload
    ansible.builtin.systemd:
      daemon_reexec: yes
      scope: user